### ISSUE TITLE
构建失败后无法继续构建

### ISSUE THREAD

**Issue by ysicing** [kplcloud/kplcloud#21]
Jenkins那边已经构建失败了，或者提示入队列错误

<img width="530" alt="企业微信截图_553f43de-b424-4e6a-a91e-44d5cb5444bd" src="https://user-images.githubusercontent.com/8605565/71581337-acc8db80-2b3f-11ea-8309-89198ad8c0a0.png">

**Comment by icowan** [comment]
@ysicing 暂停上一个构建，同一个应用只能有一个正在构建的应用
