### ISSUE TITLE
创建项目 创建模版保存时报jwt错

### ISSUE THREAD

**Issue by huanzui** [kplcloud/kplcloud#25]
创建项目 创建模版保存时报错

gitlab配置了
[git]
    git_type = gitlab
    git_addr = http://10.3.87.50:8888
    token = xxx

token 在gitlab中配置了

页面能够获得gitlab中项目的tag

在保存时报错

在方法saveJenkins
/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/kplcloud/kplcloud/src/util/helper.GitName(0xc0003c0d80, 0x2c, 0xc00016e118, 0xc0003ec400)
	/go/src/github.com/kplcloud/kplcloud/src/util/helper/functions.go:40 +0x1c8
github.com/kplcloud/kplcloud/src/pkg/project.(*service).saveJenkins(0xc000303d00, 0xc00045e200, 0xc0003d6d00, 0x9, 0x10, 0xc0007b9790, 0x1, 0x1, 0xc0003c0d80, 0x2c, ...)
	/go/src/github.com/kplcloud/kplcloud/src/pkg/project/service.go:1040 +0x50
github.com/kplcloud/kplcloud/src/pkg/project.(*service).BasicPost(0xc000303d00, 0x1c89f20, 0xc0007a94a0, 0xc0003c082c, 0x6, 0xc0003d6d00, 0x9, 0x10, 0xc0007b9790, 0x1, ...)
	/go/src/github.com/kplcloud/kplcloud/src/pkg/project/service.go:459 +0xa72
github.com/kplcloud/kplcloud/src/pkg/project.(*loggingService).BasicPost(0xc000598080, 0x1c89f20, 0xc0007a94a0, 0xc0003c082c, 0x6, 0xc0003d6d00, 0x9, 0x10, 0xc0007b9790, 0x1, ...)
	/go/src/github.com/kplcloud/kplcloud/src/pkg/project/logging.go:55 +0x166
github.com/kplcloud/kplcloud/src/pkg/project.makeBasicPostEndpoint.func1(0x1c89f20, 0xc0007a94a0, 0x17cb400, 0xc0006fab40, 0xc000612c60, 0xc0007a94a0, 0x17123a0, 0x3)
	/go/src/github.com/kplcloud/kplcloud/src/pkg/project/endpoint.go:98 +0x150
github.com/kplcloud/kplcloud/src/middleware.NamespaceMiddleware.func1.1(0x1c89f20, 0xc0007a94a0, 0x17cb400, 0xc0006fab40, 0x16a2f60, 0xc000612ca0, 0x1c89f20, 0xc0007a94a0)
	/go/src/github.com/kplcloud/kplcloud/src/middleware/asd.go:132 +0x41d
github.com/kplcloud/kplcloud/src/middleware.CheckAuthMiddleware.func1.1

**Comment by icowan** [comment]
@huanzui 有没有全一起的错误信息

**Comment by icowan** [comment]
@huanzui  git 地址不能用端口号
